# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-17 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='\n                Designates whether this user should be treated as active.\n                 Un-select this instead of deleting accounts.\n            ', verbose_name='active'),
        ),
    ]
